### ISSUE TITLE
サーバーの推奨設定について

### ISSUE THREAD

**Issue by creativival** [Jumpaku/JumpakuOthello#11]
サーバーの推奨設定はどういったものでしょうか？
JumpakuOthello API を使った音声アプリ「音声オセロ」を開発しています。
AWS Lightsail (512 MB RAM、1 vCPU、20 GB のSSD)
で Dockerコンテナを運用していますが、応答速度が遅くクラッシュしてしまいます。サーバーのグレードアップを考えています。予算もありますので、RAM 2G のコースにしようと思いますが、いかがでしょうか？　その他注意点はありますか？

（環境）
音声アプリ（Actions on Google）は Heroku + Node.js + MongoDB にて運用
Dockerコンテナ　AWS Lightsail (512 MB RAM、1 vCPU、20 GB のSSD) => アップグレード予定

（接続）
一回の応答で最大4回のAPI への問い合わせが発生します。
ユーザーが駒を置く
AI の置ける駒の評価を取得（ユーザーの設定したAI強度によって、最善手、次善手、3番手を置く駒として選ぶ）
AI の駒を置く
ユーザーが置ける駒のAI による評価を取得（次の盤面に「強い=赤」「弱い=青」で評価を表示する）

アプリ自体へのアクセスですが、今は宣伝していないので少ないです。完成後は、日本語と英語対応なのでアクセスは増えると見越しています。ご助言をお願いします。

**Comment by creativival** [comment]
無理なお願いかと思いますが、API への問い合わせの回数を減らしたいです。4回を２回に減らしたい。
「ユーザーが駒を置く」のレスポンスに「（次に）AI の置ける駒の評価」を加える。
「AI の駒を置く」のレスポンスに「（次に）ユーザーが置ける駒のAI による評価」を加える。
これは別の issue になりますが、サーバー設定にも関連するので追記しました。ご検討ください。

**Comment by Jumpaku** [comment]
サーバーの推奨設定については特に見積もってないため，わかりません．参考までに，私が試した動作環境を以下に示します．

 * MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)
  OS：macOS Catalina
  プロセッサ：3.1 GHz Dual-Core Intel Core i5
  メモリ：16 GB 2133 MHz LPDDR3
 * さくらのVPS（2GB）
 OS：Ubuntu
 プロセッサ：仮想3Core
 メモリ：2GB

これらの動作環境では，APIがAIの選択した手を返すのに数秒を要することがありますが，JumpakuOthelloの「クラッシュ」は確認できていません．詳しく調べるためには「クラッシュ」が具体的にどのような動作なのか教えていただければと思います．

もし，JumpakuOthelloのAPIがAIの選択した手を返すのに数秒を要することが原因で「クラッシュ」しているのだとすると，APIの呼び出し元またはAWS Lightsail上のリバースプロキシなどにタイムアウトの設定があるのではないかと思いますので，そこを変更することができれば解決するように思います．

もし，例えばAWS Lightsailの仕様としてタイムアウトが設定されており，それを変えられないとすると，まずは，そのタイムアウトの時間を教えていただきたく思います．

私は，JumpakuOthelloのパフォーマンスの低さと「クラッシュ」の因果関係がはっきりしていない段階でのサーバーのグレードアップはするべきでないと考えます．

**Comment by Jumpaku** [comment]
https://github.com/Jumpaku/JumpakuOthello/issues/11#issuecomment-705264375

ご提案ありがとうございます．JumpakuOthelloの対戦に関するAPIは，人間同士の対戦，AIと人間の対戦，AI同士の対戦を区別すること無く処理できるように実装しています．また，AIに関するAPIは，手の選択機能単体で動作できるよう，対戦に関するAPIとは分離しています．現状で必要十分なAPIを提供できていると考えているため，対戦機能とAIの機能を組み合わせたAPIを追加する考えはありません．

**Comment by creativival** [comment]
![dialogflow_heroku_lightsail](https://user-images.githubusercontent.com/33368327/95417865-097be100-0971-11eb-8608-8cb511c634ec.png)

ご回答ありがとうございます。こちらの環境は以下となります。

開発　iMac 27inch late 2012 (MacOS Mojava)
本番　AWS Lightsail Ubuntu (512 MB RAM、1 vCPU、20 GB のSSD)東京、ゾーン A (ap-northeast-1a)

両方で生じるエラーなのですが、
① Webhook で Heroku に問い合わせ
②->③->②->③->②->③->②->③-> でオセロ盤の作成とテキスト（読み上げ用）を作成
④ Webhook で Dialogflow に返答する
の流れの中で、②->③->②->③->②->③->②->③-> で数秒の時間がかかってしまい、④が受付されないために、アプリが強制終了している状態です。

https://othello.jumpaku.net のAPI をお借りして動作確認すると、強制終了はしません。それで AWS Lightsail のパフォーマンス関係かと予測しました。

Lightsail の設定項目には「タイムアウト」関係の設定値は見つかりませんでした。Ubuntu 16.4 は初期値のまま使っています（Dockerコンテナのみ設置）。その他、調べる項目があれば教えてください。

**Comment by creativival** [comment]
対戦機能とAIの機能を組み合わせたAPIを追加する考えはありません．
-> 承知致しました。上記の②->③->②->③->②->③->②->③->工程の時間を少しでも減らしたかったものですから、無理を承知で聞かせていただきました。現在の条件での開発を継続します。

**Comment by creativival** [comment]
おさわがせしました。クラッシュはHerokuのWebhook周りの処理に原因があることがわかりました。Dialogflowの応答タイムアウトは5秒で、この制限に引っかかってアプリが強制終了してしまうようです。応答タイムアウトを伸ばす方法はないようです。
従いまして、対策として２つ試してみます。
⑴ Lightsailサーバーのアップグレード（RAM 500MB -> 2GB）。このサーバーに Wordpress を載せようと考えておりましたので、この機会にアップグレードしてみます。少なくともパフォーマンスが下がることはないでしょう。
⑵ Herokuでの処理の見直しで、「AI の置ける駒の評価を取得（ユーザーの設定したAI強度によって、最善手、次善手、3番手を置く駒として選ぶ）」の工程を省きます。AI の強度調整を元に戻して、「強い=すべて最善手」「普通=2/3最善手」「弱い=1/3最善手」にしてみます。これで処理時間が3/4以下になるはずです。
以上で、このIssueを閉じたいのですがよろしいですか？　JumapkuOthello API の将来の高速化を期待しつつ。

**Comment by Jumpaku** [comment]
JumapkuOthelloの実装上のバグがクラッシュの直接の原因となっているわけではないようですのでIssueを閉じます．しかしながら，AIの処理速度に問題があることは確かだと思いますので，AIの高速化をIssueとしてあげておきます．長い目で見ていただければと思います． #12
