### ISSUE TITLE
AIの最善手だけでなく、強い手を順番に配列で返す

### ISSUE THREAD

**Issue by creativival** [Jumpaku/JumpakuOthello#9]
ゲームである以上「勝ったり負けたり」して「自分が強くなっていく」要素が必要と思われる。そのゲーム的要素を Jumpaku Othello で実現するために、「AIの最善手だけでなく、強い手を順番に配列で返す」機能を追加してもらいたい。

例えば、ゲームを開始して、ユーザーが"19" に駒を置いた時のレスポンスに

```
"availableMoves":[18,20,34],
"strongerMoves":[20,18,34],
```

の形でAIの読んだ手を強い順で返す配列を加える。そうすることで、ユーザーの強さにより、最善手、２番手、３番手を選んで返すことで AIの強度を調整できる。

**Comment by creativival** [comment]
次の要素として、ユーザーの強さを AIの読みにどれだけ近いかで判定したい。

例えば、ゲームを開始して、ユーザーが"19"、AIが"18"に駒を置いたレスポンスに、AIがユーザーのターンなら、どこに置くかの配列を加える

```
"availableMoves":[17,26,37,44]
"strongerMoves":[44,37,26,17]
```

次のターンでユーザーが最善手"44"を選んだら、AIも最善手を返す。２番手"37"を選んだら、２番手を返すことで、自動でAIの強度を調整でき、「勝ったり負けたり」の要素が実現できるはず。

**Comment by creativival** [comment]
練習モードとして、ユーザーにAIの最善手を教えてあげる機能を加える。

例えば、上記の条件でユーザーが"26"を選んだ時に「あなたは"26"を選びました（一致度33%）。AIの最善手は"44"です。どちらを選びますか？」とアプリで表示することで、その場面での最善手を教えてあげることができる。練習モードを繰り返すことで、　AIの読みに近づくことができ、「強くなっていく」要素を実現できる。
ゲーム終了時に、「あなたの読みとAIの一致度は"59%"でした。」と示すことで、数値として自分の強さを確認できるようになる。

Jumpaku Othello に加えてもらいたい要素をまとめました。実現可能なものがあればご検討ください。

**Comment by creativival** [comment]
強い順に配列で返すと書きましたが、２つの手が同率ということがありえますね。その時の処理も考えなければなりません。

例えば、"44"と"37"が同率のレスポンスは、多重配列にするなど、いかがでしょうか。

```
"availableMoves":[17,26,37,44]
"strongerMoves":[[44,37],26,17]
```

**Comment by Jumpaku** [comment]
新機能の提案をしていただきありがとうございます．提案いただいた機能を実装するためのAPIについて以下のように考えております．いかがでしょうか？

## 選択可能な手を評価するAPIの追加

AIの最善手以外の手を利用するために選択可能な手を評価する以下のAPIを追加しようと思います．APIの利用者はこのAPIを利用することで，ユーザの手とAIの手を比較する機能やユーザにAIの候補手を伝える機能を実装できるようなります．

### 選択可能な手を評価するAPI

| URI Path | Method | Request body type | Response body type |
|--------|---------|--------------------|---------------------|
| `origin`/v1/ai/moves | POST | `{ selectPlayer: Disc, board: Board }` | ` MovesResult` |

```ts
type MovesResult = { moves: EvaluatedMove[] } | Error;
type EvaluatedMove = { move: number: evaluation: number };
```

### 動作例のイメージ

#### リクエスト

```sh
curl -X POST https://othello.jumpaku.net/v1/ai/moves -d '{ "board": { "darkDiscs": [19,27,28,35], "lightDiscs": [36] }, "selectPlayer": "Light" }'
```

#### レスポンス

```json
{
  "moves": [
    { "move": 18, "evaluation": 1035 },
    { "move": 20, "evaluation": 24 },
    { "move": 34, "evaluation": -348 }
  ]
}
```

もし置ける場所が無いなら `{ "moves": [] }`が返される.

## ゲーム中にAIの強さを調節するためのAPIの検討

ユーザーの強さに応じてAIの強さを変更するためには，局面を評価する機能とAIの読みの深さを調整する機能を利用する方が良いと思います．例えば，AIが優勢なときはAIの読みを浅くし，AIが劣勢なときはAIの読みを深くします．この機能を実装するために以下のAPIを追加するのが良いと思います．このAPIについては強い手を順番に配列で返すものでは無いため別のIssueで検討したいと思います．

|| URI Path | Method | Request body type | Response body type |
|---|--------|---------|--------------------|---------------------|
|読みの深さを指定してAIの最善手を得る| `origin`/v1/ai/move | POST | `{ selectPlayer: Disc, board: Board, depth: number? }` | `MoveResult` |
|読みの深さを指定して選択可能な手のAIによる評価を得る| `origin`/v1/ai/moves | POST | `{ selectPlayer: Disc, board: Board, depth: number? }` | `MovesResult` |
|局面の優劣を数値化として得る| `origin`/v1/ai/eval | POST | `{ selectPlayer: Disc, board: Board }` | `EvalResult ` |

```ts
type EvalResult = { evaluation: number } | Error
```

**Comment by creativival** [comment]
素晴らしいです。私が想像していた以上の実装です。ぜひ実現していただきたいです。

## 選択可能な手を評価するAPIの追加

教えていただきたいのですが、評価数値はプラスが強いと思いますが、どういった単位なのでしょう？　その局面の優劣の値が、その手を選ぶとプラス、マイナスするイメージでよいですか？

現在の「音声オセロ」における AI の強度調整ですが、かなり手抜きしておりまして、「強いはすべて最善手」「普通は 2/3 最善手 1/3 ランダム」「弱いは 1/3 最善手 2/3 ランダム」の実装になっています。
これを改めて、「強いはすべて最善手」「普通はすべて評価値 0付近のプラス」「弱いはすべて評価値マイナス」の実装にしてみます。その方が、ランダム要素が少なくなり、強さが安定するように思うからです。

「練習モード」では、プラス（赤）0（紫）マイナス（青）で、選択可能な番号を色付け（グラデーション）することで、ユーザーが一目でその手の優劣がわかるようにしたいです。このモードを繰り返せば、色々な局面での最善手が感覚として身につくのではないかと考えました。

私のイメージしていた機能は、このAPI で実現できそうです。

## ゲーム中にAIの強さを調節するためのAPIの検討

こちらのAPI は私の理解を超えています。詳細はお任せいたします。

「音声オセロ」に実装することだけを考えると、バックエンドでの処理はわからなくてもいいので、AI の手を

```
move: '18', // 最善手
adjustedMove: '20', // 調整された指し手
```

の形で、「調整された指し手」を返してもらうと助かります。

よろしくお願いいたします。

**Comment by Jumpaku** [comment]
「手Mの評価値がYである」とは，自分がMを選択した後に最善手を選択し続けることで，将来の局面の評価値をY以上にできることを表します．局面の評価値は盤面の状態から算出される数値で局面の優劣を表します．局面の評価値に単位はありません．局面の評価値は優勢であるほど大きな正の値，劣勢であるほど小さな負の値，互角の時は0に近い値となります．また，自分にとっての局面の評価値がYの時，相手にとっての局面の評価値は-Yとなります．

ここまでの方針で，選択可能な手を評価するAPIの追加を行ってみようと思います．

**Comment by creativival** [comment]
ご説明ありがとうございます。何となくですが理解しました。AI をもっと勉強したいと思います。

こちらも「音声オセロゲーム（<= 呼び出すやすいように改称しました）」の改造を続けており、Interactive Canvas のオセロボードの数字を押して、駒を選べるようにしました。現在、Googleの審査に上げています。

**Comment by Jumpaku** [comment]
選択可能な手を評価するAPIの追加を完了いたしました．
